# AI: below section was generated by an AI
import io
import builtins
import subprocess
import sys
import unittest
from contextlib import redirect_stdout
from pathlib import Path
from unittest.mock import Mock, call, patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from auto_flash import (
    Device,
    PREFLIGHT_ENVIRONMENTS,
    WLEDAutoFlasher,
    esptool_dependencies_available,
    environment_for_device_type,
    host_can_build_environment,
)


class AutoFlashTest(unittest.TestCase):
    def create_flasher(self):
        with redirect_stdout(io.StringIO()):
            return WLEDAutoFlasher(enable_sounds=False)

    def test_parses_documented_usb_serial_devices(self):
        output = """/dev/cu.usbserial-110
---------------------
Hardware ID: USB VID:PID=1A86:7523 LOCATION=1-1
Description: USB Serial

/dev/cu.usbserial-210
---------------------
Hardware ID: USB VID:PID=10C4:EA60 LOCATION=2-1
Description: CP2102 USB to UART Bridge Controller
"""

        devices = self.create_flasher()._parse_device_list(output)

        self.assertEqual([device.port for device in devices], [
            "/dev/cu.usbserial-110",
            "/dev/cu.usbserial-210",
        ])
        self.assertEqual([device.device_type for device in devices], [
            "unknown",
            "unknown",
        ])

    def test_selects_dedicated_universe_environments(self):
        self.assertEqual(environment_for_device_type("esp8266"), "universe_esp8266_2m")
        self.assertEqual(environment_for_device_type("esp32"), "universe_esp32dev")
        self.assertIsNone(environment_for_device_type("unknown"))

    def test_reports_missing_esptool_dependencies(self):
        original_import = builtins.__import__

        def import_without_esptool(name, *args, **kwargs):
            if name in {"esptool", "intelhex"}:
                raise ModuleNotFoundError(name)
            return original_import(name, *args, **kwargs)

        with patch("builtins.__import__", side_effect=import_without_esptool):
            self.assertFalse(esptool_dependencies_available())

    @patch.object(WLEDAutoFlasher, "_find_esptool_command", return_value=["esptool"])
    @patch("auto_flash.subprocess.run")
    def test_probes_identical_ch340_adapters_for_mcu_type(self, run_mock, _find_mock):
        run_mock.side_effect = [
            subprocess.CompletedProcess([], 0, "Chip is ESP8266EX", ""),
            subprocess.CompletedProcess([], 0, "Chip is ESP32-D0WD-V3", ""),
        ]
        flasher = self.create_flasher()

        self.assertEqual(flasher._probe_device_type("/dev/cu.usbserial-110"), "esp8266")
        self.assertEqual(flasher._probe_device_type("/dev/cu.usbserial-210"), "esp32")
        self.assertEqual(run_mock.call_args_list, [
            call(
                [
                    "esptool",
                    "--port", "/dev/cu.usbserial-110",
                    "--connect-attempts", "3",
                    "chip_id",
                ],
                capture_output=True,
                text=True,
                timeout=30,
            ),
            call(
                [
                    "esptool",
                    "--port", "/dev/cu.usbserial-210",
                    "--connect-attempts", "3",
                    "chip_id",
                ],
                capture_output=True,
                text=True,
                timeout=30,
            ),
        ])

    @patch.object(WLEDAutoFlasher, "_find_esptool_command", return_value=["esptool"])
    @patch("auto_flash.subprocess.run")
    def test_probe_failure_does_not_guess_mcu_type(self, run_mock, _find_mock):
        run_mock.return_value = subprocess.CompletedProcess(
            [], 2, "", "Failed to connect to device"
        )

        with redirect_stdout(io.StringIO()):
            device_type = self.create_flasher()._probe_device_type("/dev/cu.usbserial-110")

        self.assertEqual(device_type, "unknown")

    @patch("auto_flash.host_can_build_environment", return_value=True)
    @patch("auto_flash.subprocess.run")
    def test_preflight_builds_all_environments(self, run_mock, _host_mock):
        run_mock.side_effect = [
            subprocess.CompletedProcess([], 0)
            for _ in PREFLIGHT_ENVIRONMENTS
        ]

        with redirect_stdout(io.StringIO()):
            result = self.create_flasher().preflight_firmware()

        self.assertEqual(result, set(PREFLIGHT_ENVIRONMENTS))
        self.assertEqual(run_mock.call_args_list, [
            call(["pio", "run", "-e", environment], text=True, timeout=900)
            for environment in PREFLIGHT_ENVIRONMENTS
        ])

    @patch("auto_flash.host_can_build_environment", return_value=True)
    @patch("auto_flash.subprocess.run")
    def test_preflight_continues_after_failed_build(self, run_mock, _host_mock):
        run_mock.side_effect = [
            subprocess.CompletedProcess([], 1),
            subprocess.CompletedProcess([], 0),
        ]

        with redirect_stdout(io.StringIO()):
            result = self.create_flasher().preflight_firmware()

        self.assertEqual(result, {PREFLIGHT_ENVIRONMENTS[1]})
        self.assertEqual(run_mock.call_count, 2)

    @patch("auto_flash.host_can_build_environment", return_value=True)
    @patch("auto_flash.subprocess.run")
    def test_preflight_continues_after_timeout(self, run_mock, _host_mock):
        run_mock.side_effect = [
            subprocess.TimeoutExpired(
                ["pio", "run", "-e", PREFLIGHT_ENVIRONMENTS[0]],
                900,
            ),
            subprocess.CompletedProcess([], 0),
        ]

        with redirect_stdout(io.StringIO()):
            result = self.create_flasher().preflight_firmware()

        self.assertEqual(result, {PREFLIGHT_ENVIRONMENTS[1]})

    @patch("auto_flash.host_can_build_environment")
    @patch("auto_flash.subprocess.run")
    def test_preflight_skips_unsupported_environment(self, run_mock, host_mock):
        host_mock.side_effect = [False, True]
        run_mock.return_value = subprocess.CompletedProcess([], 0)

        output = io.StringIO()
        with redirect_stdout(output):
            result = self.create_flasher().preflight_firmware()

        self.assertEqual(result, {PREFLIGHT_ENVIRONMENTS[1]})
        self.assertIn("Rosetta is required", output.getvalue())
        run_mock.assert_called_once_with(
            ["pio", "run", "-e", PREFLIGHT_ENVIRONMENTS[1]],
            text=True,
            timeout=900,
        )

    @patch("auto_flash.platform.machine", return_value="arm64")
    @patch("auto_flash.platform.system", return_value="Darwin")
    @patch("auto_flash.subprocess.run")
    def test_detects_missing_rosetta(self, run_mock, _system_mock, _machine_mock):
        run_mock.return_value = subprocess.CompletedProcess([], 1)

        self.assertFalse(host_can_build_environment("universe_esp8266_2m"))
        self.assertTrue(host_can_build_environment("universe_esp32dev"))

    @patch("auto_flash.subprocess.run")
    def test_flash_uses_prebuilt_firmware(self, run_mock):
        run_mock.return_value = subprocess.CompletedProcess([], 0)
        flasher = self.create_flasher()
        flasher.erase_flash = False
        device = Device(
            port="/dev/cu.usbserial-210",
            hardware_id="USB VID:PID=10C4:EA60",
            description="CP2102 USB to UART Bridge Controller",
            location="2-1",
            device_type="esp32",
        )

        with redirect_stdout(io.StringIO()):
            result = flasher.flash_device(device)

        self.assertTrue(result)
        run_mock.assert_called_once_with(
            [
                "pio", "run",
                "-e", "universe_esp32dev",
                "--target", "upload",
                "--upload-port", "/dev/cu.usbserial-210",
            ],
            capture_output=True,
            text=True,
            timeout=300,
        )

    @patch("auto_flash.subprocess.run")
    def test_flash_stops_when_erase_fails(self, run_mock):
        run_mock.return_value = subprocess.CompletedProcess(
            [], 1, "", "erase failed"
        )
        flasher = self.create_flasher()
        device = Device(
            port="/dev/cu.usbserial-110",
            hardware_id="USB VID:PID=1A86:7523",
            description="USB Serial",
            location="1-1",
            device_type="esp8266",
        )

        with redirect_stdout(io.StringIO()):
            result = flasher.flash_device(device)

        self.assertFalse(result)
        run_mock.assert_called_once_with(
            [
                "pio", "run",
                "-e", "universe_esp8266_2m",
                "--target", "erase",
                "--upload-port", "/dev/cu.usbserial-110",
            ],
            capture_output=True,
            text=True,
            timeout=60,
        )

    def test_unavailable_device_is_skipped(self):
        flasher = self.create_flasher()
        flasher.available_environments = {"universe_esp32dev"}
        device = Device(
            port="/dev/cu.usbserial-110",
            hardware_id="USB VID:PID=1A86:7523",
            description="USB Serial",
            location="1-1",
            device_type="esp8266",
        )

        with redirect_stdout(io.StringIO()):
            flasher.start_flash_for_device(device)

        self.assertIn(device.port, flasher.processed_devices)
        self.assertNotIn(device.port, flasher.active_flashes)

    @patch("auto_flash.threading.Thread")
    def test_ch340_esp32_flashes_when_esp8266_is_unavailable(self, thread_mock):
        flasher = self.create_flasher()
        flasher.available_environments = {"universe_esp32dev"}
        flasher._probe_device_type = Mock(return_value="esp32")
        device = Device(
            port="/dev/cu.usbserial-210",
            hardware_id="USB VID:PID=1A86:7523",
            description="USB Serial",
            location="2-1",
        )

        with redirect_stdout(io.StringIO()):
            flasher.start_flash_for_device(device)

        self.assertEqual(device.device_type, "esp32")
        self.assertIn(device.port, flasher.processed_devices)
        thread_mock.return_value.start.assert_called_once_with()


if __name__ == "__main__":
    unittest.main()
# AI: end
